# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - censorpro-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Set to Linux for path consistency
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    # Keep defaults, but override in steps for robustness
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 1. Install dependencies (explicitly set working-directory on run step)
      - name: Install dependencies (in Backend directory)
        run: npm ci
        working-directory: ./Backend # <--- Added explicitly here

      # 2. Build and Test (explicitly set working-directory on run step)
      - name: Build and Test
        run: |
          npm run build --if-present
          npm run test --if-present
        working-directory: ./Backend # <--- Added explicitly here

      # 3. Upload the Backend folder contents as the artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Backend # Relative to the repository root

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_20BBF8C015264FDEB7AECB6EC51640D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4D3D2D4A94044B2BAED119BC22A1908F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_502EC897C8F541C6A8789E4B1A409A3E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'censorpro-backend'
          slot-name: 'Production'
          package: .
